#### 1.public_sst_data.iloc[start_idx:end_idx]
    pandas.DataFrame.iloc[]
    iloc 是 pandas DataFrame 的整数位置索引方法
    它通过行号（从0开始的整数）来选取数据
    iloc[start:end] 选取从 start 行到 end-1 行的数据（左闭右开区间）

In [3]:
import pandas as pd

mydict = [
    {'a': 1, 'b': 2, 'c': 3, 'd': 4},
    {'a': 100, 'b': 200, 'c': 300, 'd': 400},
    {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]

df = pd.DataFrame(mydict)  #  key 为列名, value 为行数据
df

      a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [4]:
df.iloc[0]

a    1
b    2
c    3
d    4
Name: 0, dtype: int64

In [5]:
df.iloc[0]['a']  # 第0行的a列

1

In [6]:
df.iloc[1]  # 第1行

a    100
b    200
c    300
d    400
Name: 1, dtype: int64

In [7]:
df.iloc[0:2]  # 第0行到第1行

     a    b    c    d
0    1    2    3    4
1  100  200  300  400

#### 2.pandas.DataFrame.iterrows()
    iterrows() 是 DataFrame 的迭代器方法
    它按行遍历 DataFrame，每次返回一个包含行索引和行数据的元组
    语法：for index, row in dataframe.iterrows():

In [11]:
mydict = [
    {'a': 1, 'b': 2, 'c': 3, 'd': 4},
    {'a': 100, 'b': 200, 'c': 300, 'd': 400},
    {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]

df = pd.DataFrame(mydict)  #  key 为列名, value 为行数据
df

      a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [16]:
for index, row in df.iterrows():
    print(f"第 {index} 行")
    print(row)
    print("------------------")

第 0 行
a    1
b    2
c    3
d    4
Name: 0, dtype: int64
------------------
第 1 行
a    100
b    200
c    300
d    400
Name: 1, dtype: int64
------------------
第 2 行
a    1000
b    2000
c    3000
d    4000
Name: 2, dtype: int64
------------------